POST http://localhost:3000/register/
Content-Type: application/json


{
  "username": "vinay143",
  "name": "vinay kumar",
  "password": "rich@vinay",
  "gender": "male",
  "location": "hyd"
}
###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"vinay143",
    "password":"rich@vinay"
}

###
POST http://localhost:3000/change-password/
Content-Type: application/json

{
    "username":"vinay143",
    "oldPassword":"rich@vinay",
    "newPassword":"rich@vinay"
}